# Setup
output_file: data.nc
constants_file: constants_tio2.yaml
# root_dir: /home/sharrison/OneDrive/ceh/projects/nanofase/data
root_dir: C:/users/sharrison/OneDrive - NERC/ceh/projects/nanofase/data
iso3: GBR
time:
  n: 365
  dt: 86400
  start_date: 2018-01-01

# Meteorological and hydrological
flow_dir:
  type: raster
  path: interim/flowdir_05000_thames.tif
  crs: EPSG:27700
runoff:
  type: csv
  path: processed/model-preprocessed/runoff/runoff_2015.csv
  units: mm/day
precip:
  type: raster
  path: interim/rainfall/rainfall_5km_2015-{t}.tif
  units: mm/day
  t_min: 1
  source: CEH Gridded Estimates of Areal Rainfall (CEH - GEAR) - Daily rainfall (mm) 1km resolution for year 2000 - Great Britain. Resampled to 5 km resolution.
  references: Tanguy, M., Prosdocimi, I., Keller, V.D.J., Terry, J., Cole, S.J., Morris, D.G., Dixon, H. (2014). Consolidation of a CEH reference rainfall dataset for hydrological purposes for the UK. CEH-Wallingford, Oxfordshire, UK.

# Soil
soil_bulk_density:
  type: raster
  units: t/m**3
  path: interim/soil/bulk-density_osgb_5km.tif
  source: European Soil Data Centre topsoil physical properties resampled to OS National Grid (ESPG:27700) by bilinear interpolation. See https://esdac.jrc.ec.europa.eu/content/topsoil-physical-properties-europe-based-lucas-topsoil-data.
soil_water_content_field_capacity:
  type: raster
  path: processed/model-preprocessed/soil_wc-fc.tif
  source: European Soil Data Centre soil hydraulic properties resampled to OS National Grid (ESPG:27700) by bilinear interpolation. See https://esdac.jrc.ec.europa.eu/content/maps-indicators-soil-hydraulic-properties-europe.
soil_water_content_saturation:
  type: raster
  path: processed/model-preprocessed/soil_wc-sat.tif
  source: European Soil Data Centre soil hydraulic properties resampled to OS National Grid (ESPG:27700) by bilinear interpolation. See https://esdac.jrc.ec.europa.eu/content/maps-indicators-soil-hydraulic-properties-europe
soil_hydraulic_conductivity:
  type: raster
  units: cm/day
  path: processed/model-preprocessed/soil_ks.tif
  source: European Soil Data Centre soil hydraulic properties resampled to OS National Grid (ESPG:27700) by bilinear interpolation. See https://esdac.jrc.ec.europa.eu/content/maps-indicators-soil-hydraulic-properties-europe
soil_texture_sand_content:
  type: raster
  path: processed/model-preprocessed/sand-content_osgb_5000m.tif
  source: European Soil Data Centre soil texture dataset resampled to OS National Grid (ESPG:27700) by bilinear interpolation.
soil_texture_clay_content:
  type: raster
  path: processed/model-preprocessed/clay-content_osgb_5000m.tif
  source: European Soil Data Centre soil texture dataset resampled to OS National Grid (ESPG:27700) by bilinear interpolation.
soil_texture_silt_content:
  type: raster
  path: processed/model-preprocessed/silt-content_osgb_5000m.tif
  source: European Soil Data Centre soil texture dataset resampled to OS National Grid (ESPG:27700) by bilinear interpolation.
soil_texture_coarse_frag_content:
  type: raster
  path: processed/model-preprocessed/coarse-frag-content_osgb_5000m.tif
  source: European Soil Data Centre soil texture dataset resampled to OS National Grid (ESPG:27700) by bilinear interpolation.
soil_usle_c_factor:
  type: raster
  path: processed/model-preprocessed/c-factor_osgb_5000m_qgis.tif
  source: European Soil Data Centre soil texture dataset resampled to OS National Grid (ESPG:27700) by bilinear interpolation.
soil_usle_ls_factor:
  type: raster
  path: processed/model-preprocessed/ls-factor_osgb_5000m.tif
  source: European Soil Data Centre soil texture dataset resampled to OS National Grid (ESPG:27700) by bilinear interpolation.
soil_usle_p_factor:
  type: raster
  path: processed/model-preprocessed/p-factor_osgb_5000m.tif
  source: European Soil Data Centre soil texture dataset resampled to OS National Grid (ESPG:27700) by bilinear interpolation.


# Land use
land_use:
  type: raster
  path: processed/model-preprocessed/land-use.tif
is_estuary:
  type: raster
  path: processed/grid/is-river-an-estuary.tif

# Emissions - areal
emissions_areal_soil_pristine:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_areal_tio2_soil_pristine_2018_interp.tif
  units: kg/m**2/year
emissions_areal_soil_matrixembedded:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_areal_tio2_soil_matrix-embedded_2018_interp.tif
  units: kg/m**2/year
emissions_areal_soil_transformed:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_areal_tio2_soil_transformed_2018_interp.tif
  units: kg/m**2/year
emissions_areal_water_pristine:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_areal_tio2_water_pristine_2018_interp.tif
  units: kg/m**2/year
emissions_areal_water_matrixembedded:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_areal_tio2_water_matrix-embedded_2018_interp.tif
  units: kg/m**2/year
emissions_areal_water_transformed:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_areal_tio2_water_transformed_2018_interp.tif
  units: kg/m**2/year

# Emissions - point
emissions_point_water_pristine:
  type: shapefile
  value_var: e_2018
  path: processed/model-preprocessed/emissions/emissions_point_tio2_water_pristine_2000-2020_interp/emissions_point_tio2_water_pristine_2000-2020_interp.shp
  source_type_col: profile
  temporal_profile:
    path: processed/model-preprocessed/emissions/emissions_temporal-profile_2015.csv
    source_type_col: Emission_source_type
    for_source_type: P2
    factor_col: Factor
  units: kg/year
emissions_point_water_matrixembedded:
  type: shapefile
  value_var: e_2018
  path: processed/model-preprocessed/emissions/emissions_point_tio2_water_matrix-embedded_2000-2020_interp/emissions_point_tio2_water_matrix-embedded_2000-2020_interp.shp
  source_type_col: profile
  temporal_profile:
    path: processed/model-preprocessed/emissions/emissions_temporal-profile_2015.csv
    source_type_col: Emission_source_type
    for_source_type: P2
    factor_col: Factor
  units: kg/year
emissions_point_water_transformed:
  type: shapefile
  value_var: e_2018
  path: processed/model-preprocessed/emissions/emissions_point_tio2_water_transformed_2000-2020_interp/emissions_point_tio2_water_transformed_2000-2020_interp.shp
  source_type_col: profile
  temporal_profile:
    path: processed/model-preprocessed/emissions/emissions_temporal-profile_2015.csv
    source_type_col: Emission_source_type
    for_source_type: P2
    factor_col: Factor
  units: kg/year

# Emissions - atmospheric
emissions_atmospheric_drydepo_pristine:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_atmospheric_drydepo_tio2_pristine_2015/{t}.tif
  units: kg/m**2/s
  t_min: 1
emissions_atmospheric_drydepo_matrixembedded:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_atmospheric_drydepo_tio2_matrix-embedded_2015/{t}.tif
  units: kg/m**2/s
  t_min: 1
emissions_atmospheric_drydepo_transformed:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_atmospheric_drydepo_tio2_transformed_2015/{t}.tif
  units: kg/m**2/s
  t_min: 1
emissions_atmospheric_wetdepo_pristine:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_atmospheric_wetdepo_tio2_pristine_2015/{t}.tif
  units: kg/m**2/s
  t_min: 1
emissions_atmospheric_wetdepo_matrixembedded:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_atmospheric_wetdepo_tio2_matrix-embedded_2015/{t}.tif
  units: kg/m**2/s
  t_min: 1
emissions_atmospheric_wetdepo_transformed:
  type: raster
  path: processed/model-preprocessed/emissions/emissions_atmospheric_wetdepo_tio2_transformed_2015/{t}.tif
  units: kg/m**2/s
  t_min: 1